# Generated by Django 5.2.8 on 2025-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tablero', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('dificultad', models.CharField(default='media', max_length=20)),
            ],
        ),
    ]
