# Generated by Django 5.2.8 on 2025-11-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudoku',
            name='tablero',
        ),
        migrations.AddField(
            model_name='sudoku',
            name='tablero_actual',
            field=models.TextField(blank=True, help_text='Estado actual del tablero', null=True),
        ),
        migrations.AddField(
            model_name='sudoku',
            name='tablero_inicial',
            field=models.TextField(blank=True, help_text='Tablero de partida(JSON9x9)', null=True),
        ),
        migrations.AddField(
            model_name='sudoku',
            name='tablero_solucion',
            field=models.TextField(blank=True, help_text='solucion completa del tablero', null=True),
        ),
        migrations.AlterField(
            model_name='sudoku',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], default='media', max_length=20),
        ),
    ]
