# Generated by Django 6.0.5 on 2026-09-23 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0004_convertir_tableros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sudoku',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='sudoku',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='sudoku',
            name='tablero_actual',
        ),
        migrations.RemoveField(
            model_name='sudoku',
            name='tablero_inicial',
        ),
        migrations.RemoveField(
            model_name='sudoku',
            name='tablero_solucion',
        ),
        migrations.AlterField(
            model_name='sudoku',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], db_index=True, default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='sudoku',
            name='puzzle',
            field=models.CharField(help_text='81 dígitos, 0 = casilla vacía', max_length=81),
        ),
        migrations.AlterField(
            model_name='sudoku',
            name='solucion',
            field=models.CharField(editable=False, max_length=81),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('ganada', 'Ganada'), ('perdida', 'Perdida')], default='en_curso', max_length=10)),
                ('tablero', models.CharField(max_length=81)),
                ('notas', models.JSONField(blank=True, default=dict, help_text='{"40": [1, 8]}: notas por casilla')),
                ('errores', models.PositiveSmallIntegerField(default=0)),
                ('pistas', models.PositiveSmallIntegerField(default=0)),
                ('segundos', models.PositiveIntegerField(default=0)),
                ('empezada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('terminada', models.DateTimeField(blank=True, null=True)),
                ('sudoku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='sudoku.sudoku')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizada'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='sudoku_part_usuario_4425ab_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'en_curso')), fields=('usuario', 'sudoku'), name='una_partida_en_curso_por_sudoku')],
            },
        ),
    ]
